# .rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  SuggestExtensions: false
  Exclude:
    - 'bin/console'
    - 'vendor/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'tasks/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
