# .rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'bin/console'
    - 'vendor/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'tasks/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 15

RSpec/NestedGroups:
  Max: 4
